version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
        - ./:/var/www
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
        - 80:80
        depends_on:
        - app
        container_name: bpartners_nginx
    app:
        container_name: bpartners_app
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: php-8.2/app
        env_file:
            - .env
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - postgres
    postgres:
        container_name: bpartners_db
        image: postgres:latest
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
                 POSTGRES_USER: 'posgres'
                 POSTGRES_PASSWORD: 'root'
                 POSTGRES_DB: 'laravel'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
volumes:
    postgres:
